name: cico--demo-admin-new
 
on:
  push:
    branches:
       - development
jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
     - name: Checkout repository
       uses: actions/checkout@v2
     - name: Setup Node.js
       uses: actions/setup-node@v2
       with:
         node-version: '16'
     - name: npm install and build 
       run: |
         npm install --legacy-peer-deps
         npm run build-prod
     - name: make zip file 
       run: |
         
         zip -r cico-demo.zip dist/
     - name: Upload artifacts
       uses: actions/upload-artifact@v3
       with:
         name: package
         path: cico-demo.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
     - name: Download package
       uses: actions/download-artifact@v3
       with:
        name: package
     - name: SSH deploy
       uses: appleboy/scp-action@v0.1.4
       with:
         host: ${{secrets.HOST}}
         username: ${{secrets.USER}}
         key: ${{secrets.KEY}}
         port: ${{secrets.PORT}}
         source: "cico-demo.zip"
         target: "/var/www/html/cico-admin-demo/"
     - name: SSH Unzip file
       uses: appleboy/ssh-action@v0.1.10
       with:
         host: ${{secrets.HOST}}
         username: ${{secrets.USER}}
         key: ${{secrets.KEY}}
         port: ${{secrets.PORT}}
         script: | 
           sudo unzip -o /var/www/html/cico-admin-demo/cico-demo.zip -d /var/www/html/cico-admin-demo/
           sudo rm /var/www/html/cico-admin-demo/cico-demo.zip